---
title: Extended Early Adulthood and Attitude Change
author:
  - Kevin Kiley, North Carolina State University
  - Nicolas Restrepo, University of California, Davis
date: "7/06/2023"
output: 
  bookdown::word_document2: 
    fig_caption: yes
    reference_docx: word-styles-reference-02.docx
  bookdown::pdf_document2:
    keep_tex: true
    latex_engine: xelatex
    toc: false
    number_sections: true
bibliography: ["kileybib.bib"]
header-includes:
   - \usepackage{setspace}
   - \setlength{\parindent}{4em}
   - \setlength{\parskip}{0em}
   - \usepackage[markers,nolists]{endfloat}
   - \usepackage{graphicx}
mainfont: Minion Pro
fontsize: 12pt
abstract: Young adulthood is consistently identified as a “formative period” in the life course, when people have heightened probability of attitude change. This probability has often been attributed to the social conditions of adolescence. Over the past 70 years, changes in the timing of major life course events such as marriage have transformed and extended this life stage. We leverage these changes to explore whether these life course changes, as well as broader social changes, have affected how likely people of different cohorts are to make durable changes of general political dispositions over a comparable time frame. We find strikingly little difference in the rates of any kind of stable opinions and opinion change among young people in different eras. People of all ages have similar attitude behaviors over time. The overall pattern suggests either that social conditions are not strongly related to attitude stability or that different social shifts have had counter-vailing effects that produce aggregate stability in rates. 


---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Introduction

Adolescence and young adulthood are typically identified in social science literature as “impressionable years” – a stage of the life course in which people are more susceptible to broad social currents, when their opinions are more malleable, and when peoples’ core ideas and attitudes are formed [@krosnick1989; @alwin1991]. Research regularly finds that people are more likely to change their attitudes and opinions in these life stages than other life stages, with opinions becoming more stable once these life stages have passed [@sears2013]. This pattern, in which young people are open to attitude change and become more resistant over time, underpins dynamics around cohortization that are frequently invoked in larger models of social change [@ryder1965; @mannheim1952].

However, why people in this life stage appear to show more frequent opinion change relative to older people is unclear. Work in biology, psychology, and cultural evolution shows that peoples’ cognition changes in ways that might make them more resistant to new information as they age. Explanations in social sciences, in contrast, tend to highlight the unique social features of these life stages – high rates of mobility between social contexts, participation in educational institutions, and cultural expectations about pursuing “new experiences” – that shape how people are exposed to new sources of information or their ability to update opinions in the face of new information. While both mechanisms likely play a role in facilitating opinion change in this life stage, the relative contributions of each are unclear.

Clarifying the mechanism that drives the frequency of opinion change during this formative period is important for understanding the broader process of social change and cultural evolution. If openness to change in early adulthood is principally a function of the social structure of life in that time period, changes in the timing and ubiquity of life course events like marriage and childbearing can have significant impacts on the broader process of macro-social change. Similarly, social changes such as the deinstitutionalization of marriage [@cherlin2004; @cherlin2021; @robbins2022] that decrease distinctions between life course stages might make older people more open to change in more recent eras than in older eras, diminishing the importance of “cohorts” for social change. If the mechanisms are principally cognitive and biological, rather than social, then these changes are unlikely to affect rates of social change in the same way.

In this paper, we seek to further elaborate this debate by exploring how changes in the broader social structure and changes in the timing of life course events since the 1950s have affected rates of change in political attitudes over time, especially differences in rates of opinion change between young adults and the rest of the population. Over the course of the 20th century, the timing of life-course transitions such as completing schooling, entering the workforce, getting married, leaving one’s parents’ home, and having children, have changed dramatically, with most of these event occurring later in the life course in more recent cohorts [@buchmann1989; @bruckner2005]. Similarly, this stage of life has become more detached from family and other role obligations, giving people more freedom to explore new ideas and lifestyle choices [@rosenfeld2009]. This suggests both a lengthening and a intensification of this stage of the life course in ways that should increase the rates at which people make changes of opinion. 

We take advantage of this change over time to explore whether young adults of different cohorts demonstrate more or less change in general political opinions over time relative to other members of the population. We compare rates of opinion change in comparable general political attitudes across four eras – 1956-1960; 1972-1976; 1992-1996; and 2006-2010 – and between young people and old people in these eras, to evaluate a range of competing hypotheses about what accounts for the divergence in attitude behaviors over the life course. 

Broadly, we find that the probability of political opinion change in people under 30 have not increased as the “early adulthood” window has lengthened and the conditions of this life stage have changed. Across eras, young people make political opinion changes at remarkably similar rates, with social transitions such as marriage, having children, and completing education playing little role in the rates at which these opinion changes happen. While these findings do not provide conclusive evidence of one mechanism over the other, they confine the range of potential theories of attitude development and the nature of political opinions. In particular, they suggest that there is something relatively timeless – potentially biological and cognitive factors – that accounts for increased opinion variance in young people. 

# Impressionable Years

The idea that the early stages of the life course are especially influential in the process of attitudinal formation is dominant across contemporary accounts of socialization [@dinas2014; @guhin2021]. The argument – at times implicit – is that the circumstances in which people are brought up leave an enduring and traceable mark on their worldviews [@gerber1998]. In the study of political socialization, this perspective enjoys a longstanding history. “Generational effects” are used to explain the development of political preferences, longitudinal shifts in attitudes, and differences across age-groups [@mannheim1952; @bartels2014] However, the notion of “impressionable years” is more general. The burgeoning literature on cohort effects rests on the assumption that our early years play key role in shaping not just political opinions, but peoples’ cognition on many dimensions (Elder 2018). Their early years will leave a mark that will be predictive of their life outcomes, well beyond those impressionable years have passed. Thus, the notion of a formative period – at the early stages of the life-course – underpins diverse and longstanding lines of research.

The “impressionable years” hypothesis – that people demonstrate more opinion change early in life followed by a period of relative stability, especially in middle age – has often been tested against other theories of opinion change over the life course. The most common are an aging stability or increasing persistence hypothesis that argues that openness to change gradually declines over time and a life stages hypothesis, in which people are open to attitude change both early in life and later in life, with stability principally happening in middle ages [@visser2004a].  While different attitudes occasionally follow different patterns, the impressionable years hypothesis has generally been shown to be true for broad political ideology, partisan identification, and specific policy preferences [@krosnick1989; @alwin1991; @sears1999]; social attitudes [@danigelis2007]; and interest in politics [@prior2010]; as well as things like personality [@wagner2019]. More generally, recent research has found that, with a few notable exceptions of high-salience events such as national shifts around gay rights, durable change of social opinion is quite rare among U.S. adults [@kiley2020], and Vaisey and Lizardo [-@vaisey2016] find that cohort explains much more variance than period for most items in the General Social Survey, suggesting a strong impressionable years pattern.

In recent years, researchers have attempted to use new approaches to quantify “openness” to social influence across the life course, especially around politics [@bartels2014; @ghitza2022]. This work has produced remarkably similar patterns with openness peaking from a person’s mid-teens through age 25 and declining quickly after that, lending more credence to the “impressionable years” hypothesis. However, this work tends to assume a constant age-based rate of openness across cohorts – that 20-year-olds in 1950 are open to influence at the same rate as 20-year-olds in 2010 – which has not been tested.

# Theoretical Models

Why is it research consistently finds the period of time between 14 and 25 to be distinctly “impressionable years?” At the outset, it is important to note that changing one’s mind involves at least two distinct processes that can be difficult to disentangle: exposure to new ideas and openness to change conditional on exposure to new ideas. For example, it could be the case that people of all ages are exposed to new ideas at similar rates, with acceptance of a new idea being a function of age, which would account for age-based patterns in opinion change. Conversely, it could be the case that rates of exposure to new ideas changes over the life course, while openness to changing one’s mind as a function of exposure does not, producing the same pattern. It could also be the case that both change as a function of age. Any patterns we observe should be interpreted as coming from changes in one or both of these processes. In this section we outline theoretical mechanisms that have been suggested to contribute to one or both of these processes. 

## Biological Mechanisms: 

The first potential mechanism for changes in attitude stability over time is biological: that the development of the of human brain as people age makes it more difficult for people to make changes of opinions after some point in their life. This approach tends to suggest that human cognition works similar to Bayesian updating (Bartels and Jackman 2014; Sherratt and Morand-Ferron 2018; Gopnik 2020). In this framework, humans weight information equally, whether they encounter it during adolescence or middle age. However, given that by the time people reach adulthood they have already encountered a lot of information, each new piece will have less of an impact (Bartels and Jackman 2014). The distinctive thing about our early years is simply that they happen early. They prove so influential because the incremental effect of new information diminishes as we age. 

It is also possible that there is something unique about human cognition during these periods: that agents ascribe more weight to the information acquired within them. Maturational arguments about the increased plasticity during our early years are consistent with this position (Mata and von Helversen 2015). Our brains exhibit more malleability during childhood and adolescence (Mata and von Helversen 2015). This is consistent with the fact that these early formative periods have been observed across species and contexts. It is not only human children that exhibit a heightened capacity to adapt. In a study of social learning among birds, for instance, Aplin et al (2017) show that younger individuals – unlike their older counterparts – were consistently able to retool their habits in light of new information.

Though the Bayesian updating explanation is simple and elegant, research across different disciplines has produced evidence that supports the existence of these periods of heightened sensitivity. In light of empirical evidence about these sensitive windows, there has been extensive modeling work about their evolution. This line of research seeks to understand why periods of heightened sensitivity would emerge and what contexts would facilitate their emergence (Fawcett and Frankenhuis 2015). The central argument is that the emergence and timing of these sensitive windows depends on the interaction between the access to information, the reliability of information, and the stability of the environment (Frankenhuis and Walasek 2020). Early formative periods are likely to evolve in specific configurations: when environments are unstable, and information is plentiful yet unreliable (Frankenhuis and Walasek 2020). In these circumstances, it makes sense for agents to explore early on, to find something that works and then to stick to strategies that have worked well in the past. Access to different types of information might vary across time and this might explain the emergence of sensitive periods at later stages of the life-course (Walasek, Frankenhuis, and Panchanathan 2021). For example, the importance of musical tastes and fashion choices becomes important around adolescence, and, at this stage, we are awash with – at best contradictory – information about what one should or should not like, should or should not wear. Sensitive periods around the development of these tastes might peak around this period, when there are more signals and when the payoffs are more salient.

The thrust of the biological arguments is that, through millennia of evolution, humans have developed a cognitive architecture that makes them relatively open changing dispositions at younger ages and relatively resistant at older ages. However, while biological mechanisms can shape how individuals respond to new information when they encounter it, these processes cannot dictate the rate at which individuals are exposed to new information, which might also matter for rates of opinion change. For that, we must turn attention to the structuring of the social world. 

## Life Course and Social Roles:

Humans’ early years might be distinct in terms of cognitive plasticity, but they are also socially distinct: they are characterized by sustained social learning and punctuated with constant changes of social contexts. Here we briefly consider some of the ways that the “impressionable years” differ in ways that might expose people to new information at higher rates and also affect their willingness to update beliefs, beyond what cognition might allow. 

First, people in this age group tend to move through social contexts much more quickly than people in other age groups. In the 11-year window from ages 14 to 25, in which people seem to show the highest rates of opinion updating, young people move from middle school to high school to either higher education or the workforce or both, with each year in these contexts potentially exposing people to new classmates, teachers, and other role models, peers, and sources of information. People in this age window also show the highest rates of residential mobility, moving for educational and occupational reasons [is this true?]. Assuming that new social contexts shape exposure to new information, this heightened contextual mobility during this stage might explain part of the difference between age groups. 

Second, people in the “impressionable years” window spend their time in different social contexts than people in middle age. Data from the American Time Use Study shows that people under age 25 spend a larger portion of the day on leisure time and educational activities and a smaller part of the day doing work and work-related activities than people between the ages of 25 and 55. These contexts, especially education, are designed to expose people to new information in ways that can lead to new opinions. For example, there is some evidence that college attendance leads to changes in opinions about civil liberties, gender egalitarianism, and racial inequality [@campbell2016; wodtke2018]. Social networks also differ in this time period. Previous work has found that young peoples’ networks tend to be larger and include more friends than kin, for example [@marsden1987].  It could be the case that larger “weak tie” networks expose younger people to more new information that drives opinion change [@granovetter1973; @burt2005]. 

Third, these are periods in which exploration and self-discovery are expected and encouraged; something that should not be taken for granted given social variation in norms around when maturity is reached [@cunningham2007; @elder1994]. 

## Updating Conditional on Exposure

While social conditions might expose young people to new information at higher rates, it might also make it easier for them to act on these new sources of information in ways that facilitate opinion change. 

Previous work on stability of attitudes over the life course suggests that people tend to value stability in figures of authority. As people move into roles with more authority in mid-life, both in family and occupational contexts, they feel this expectation from others and act accordingly, closing themselves off to updating beliefs [@eaton2009]. This potentially explains another phenomenon with some evidence behind it: that people appear to open up to changing their minds again as they enter post-retirement [@danigelis2007]. At this point, peoples’ authority diminishes, potentially opening them up to change later in life.

Similarly, mid-life is associated with more homogenous networks [@marsden1987; @diprete2011], which experimental research suggests reduces the propensity to adopt new beliefs [@visser2004]. If young people exist in less dense, more heterogeneous social networks, they might it easier to update their networks to reflect new beliefs rather than constrain their beliefs to their social networks, or close off parts of their lives to people who might not be supportive of new attitudes. 

Given the distinct social conditions of the early-adult phase of life, there are significant reasons to believe that the “impressionable years ” are principally an effect of how we have chosen to structure the life course, or the interaction between these life course stages and biological mechanisms. 

# Changing Life Course

Contemporary historical trends offer the opportunity to disentangle the role of socio-cultural and  biological factors in explaining why we observe “impressionable years.” In the U.S., the last decades have seen considerable changes around adolescence and young adulthood (Buchmann 1989; Rosenfeld 2007; Rosenfeld and Kim 2005). The expansion of higher education and increased possibilities for mobility are among the many social processes that have led to changing expectations for the trajectories that young adults should follow (Rosenfeld 2007). In general, as Buchmann  (1989) notes, life trajectories have become less predictable. The “script” of young adulthood has become less rigid: it might involve prolonged higher education, moving to a different city, or dating without a stable romantic partner. The routes that people are taking into adulthood are increasingly diverse. For the purposes of this paper, there are two accompanying trends that are particularly important: the elongation and intensification of young adulthood.

## Timing

The period between adolescence and “settling down” seems to be getting longer, and this might affect the patterns of attitudinal updating we expect to see for the same age groups in different cohorts. Buchmann (1989) notes that the diversification of life-trajectories has been accompanied by the postponement of the rituals associated with adulthood. In the U.S., the median age at first marriage has consistently risen in the last decades and so has the median age at which families are having their first child [@rosenfeld2009]. We also see higher rates of non-marital childbearing across all demographic groups [@cherlin2021]. Thus, the markers of the transition into adulthood seem to be occurring later in the life-course and potentially in different orders. Therefore, the definition of what counts as our “impressionable years” might be extending. This, in turn, could have an effect in how long exploration lasts throughout the life-course. If this is the case, we should expect to see more attitudinal updating among individuals in age-ranges that, in previous cohorts, had displayed mainly stability. In other words, people who were born say in the mid 20th century would have displayed mainly attitudinal stability by the time they reached their mid-twenties while more contemporary counterparts might still exhibit attitudinal updating when they reach that age. Adolescents are taking longer to move through the rituals of adulthood, and this might in turn elongate the period in which exploration and self-discovery are expected.

## Changing Impressionable Years:

Another second trend relates to just how much exploration young adults can engage in during these “impressionable years.” In his work, Rosenfeld (2007) explores the rapid rise in same-sex and interracial marriages in the U.S. His argument is that one of the processes underlying these changes is that young adults are increasingly escaping the controlling gaze of their parents. When young people live with – and/or financially dependent on – their parents, the latter have more say about their children’s choice of partner. The increased independence and mobility that young adults have enjoyed since the mid 20th century means that they have been able to engage in courtship outside the gaze of their parents, thus making choices that would not have been sanctioned by them. Rosenfeld’s (2007) work highlights an important insight: exploration might not be only a product of how sensitive we are to novel information but also how – and whether – we can act upon such information. The social institutions where we spend our impressionable years might shape how much exploration we can engage in. An increase in independence then might entail more exploration. This assertion in turn engenders a prediction: we should see more attitudinal updating among contemporary young adults than their older counterparts, who tended to be closer to the grip of familial control, even if they have met similar life course milestones. The contemporary social organization of young adulthood, which has been developing for the last few decades, might give rise to more meaningful attitudinal changes by providing more leeway to deviate from established social norms.

This approach suggests that it is not the timing of life events that is important for rates of change, but the broader social conditions of early adulthood that might make people more malleable in recent cohorts even net of changes. In other words, unmarried, childless 25-year-old men and women in 1956 might have experienced a set of social constraints that unmarried, childless 25-year-old men and women in 2008 do not experience, leaving the latter much more open to developing new opinions than their predecessors.

# Hypotheses

Sociological work then highlights that there are principled reasons to believe that length and intensity of formative periods might be affected by changes in the timing and structure of the life course, and yet this question remains unexplored. The distinctiveness of youth remains the backbone of sociological theories of socialization and there has been work trying to outline the cognitive assumptions that would lead to marked influence of our early years. While the evidence for these formative periods has accrued, there has been limited research on the social variability of these periods. Any evidence of differences in the rate of attitudinal updating among people of similar ages across different periods would suggest that sensitive periods are not only maturational or a result of “tallying up” information. In turn, finding similar patterns of attitudinal updating across widely different social contexts would lend further credence to the idea that our early years are “impressionable” either because we weight information more heavily during these periods or because we are cementing our opinions, regardless of the social contexts we happen to find ourselves in.

The argument so far implies three hypotheses that we will test in our study. Given historical changes in the meaning of adolescence, we hypothesize that we will see differences in the rates of attitudinal updating that the same age-groups across different cohorts will exhibit. The first hypothesis then is non-directional:

*H1: There will be differences in the patterns of attitudinal updating from individuals in the same age groups but in different cohorts.*

This does not make any specific predictions about the form of attitudinal updating that more recent cohorts of young people will exhibit, just that their opinion reports will be more variable than that of previous cohorts.

The second hypothesis is based on Buchmann’s work and it concerns the fact that young adults are increasingly postponing the rituals associated with the transition into adulthood. Thus, we posit that more recent cohorts should display more exploration well into their twenties than previous cohorts.

*H2: Young adults in recent cohorts should exhibit higher levels of attitudinal updating later than their counterparts of similar ages from older cohorts.*

We expect this to take the form of decreased reliability in their attitudes, as they make more transitive, non-durable changes in attitudes over time.

The last hypothesis in turn relates to Rosenfeld’s ideas. Young adults in recent cohorts have enjoyed more independence and, therefore, might have had more opportunities to substantially change their beliefs and habits. We hypothesize then that:

*H3: Young adults in recent cohorts should exhibit higher rates of attitudinal updating than people of a similar age in previous generations.*

Broadly speaking, we expect young people to be more likely to make "real" change in their attitudes, meaning their "true" values at time $t$ will be worse predictors of their true value at time $t+1$. Second, we expect young people to have more "noise" in their opinions, meaning they will have lower reliability on their opinions than other age groups as they vacillate more as a result of influences from the environment.

In particular, we focus on two age groups compared to the broader population. The first is respondents who are under 25 when they begin the survey. These respondents have typically displayed the most distinctive attitudinal patterns relative to the rest of the population, and this period has been considered the "impressionable years," at least of those that are documented in surveys [@alwin2007; @krosnick1989]. The second age group is respondents aged 26-33 when they start the survey. This group has seen the most dramatic shift in life course structuring over the past seven decades. To the extent that we see an elongation of impressionable years, we should see changes among this group.

# Data and Methods

Analyzing these questions requires data on attitude reports over time for members of different cohorts at different time points. To address this, we draw on data from seven panels administered since the 1950s. These include four major panels administered by the American National Election Study in 1956-58-60, 1972-74-76, 1992-94-96, and 2000-02-04. These were all administered over a four-year period, with waves two years apart and contain a diverse array of attitudinal questions. We also use the General Social Survey's rotating panels from 2006-10, 2008-12, 2010-2014. We also evaluate the 1980 Major Panel study from the American National Election Study. Rather than being administered three times over four years, the 1980 panel was administered three times over a single year. All seven surveys reflect nationally representative samples of U.S. households.

In all panels, we identified questions that tap several categories of political attitudes: (1) political efficacy and alienation; (2) attitudes toward social groups (such as labor unions, blacks, whites, the police, Democrats, liberals, etc.); (3) attitudes toward policy issues; (4) ideological identification on a liberal-conservative scale, and (5) partisan identification. For the 1950s, 1970s, and 1980, we broadly follow Krosnick and Alwin [-@krosnick1989] in selecting variables, with the addition of some questions about foreign policy that they omitted. In the 1990 panel, we follow Alwin's identification of questions [-@alwin2007]. For the 2000s ANES panel and the three GSS panels, we identify questions similar to those identified in the earlier panels.

This produces a set of 265 attitude measures asked on a variety of scales tapping a diverse array of topics. They include four- and five-point Likert scales, binary agree/disagree response scales, 100-point "feeling thermometers", and a range of other structures. 

Most questions are asked in only one panel, but a small number of questions are replicated exactly across at least two panels (excluding questions duplicated across the GSS panels, where all questions are duplicated). There are theoretically relevant trade-offs from focusing on the same questions over time. By focusing on the same questions over time, we control for question content and structure. If attributes of questions changes over time, that might affect the estimates of stability or reliability. However, the questions asked in major surveys change over time as the dominant issues change. By focusing only on questions that are repeated across eras, we limit our attention only to issues that have been salient for an extended period of time. These might behave different than the "issues of the day" -- they might get settled earlier in life, be more resistant to change, or be reported more reliably than other kinds of questions. 

To ensure that our findings are robust to both sets of issues, we conduct a separate analysis of questions that are repeated across multiple panels (excluding questions replicated just across the GSS). These include partisan identification (asked in all panels), political ideology on a seven-point liberal-conservative scale (asked in ## panels), questions about federal spending on different priorities (asked in the 1990 and 2000 ANES panels and the GSS panels), and questions about government efficacy and alienation from the political process (asked in the 1970s, 1990s, and 2000 ANES panels), as well as others.

## Methods of Analysis

We follow previous work that seeks to separate true change in attitude response from measurement error in the study of attitude change and stability over the life cycle. To do this, we follow Alwin and Krosnick's approach of using just-identified simplex models that specify two structural equations for a set of three over-time measures of a given variable, $y_i$:

$$ y_{t} = \tau_t + \epsilon_t$$

$$ \tau_t = \beta_{t,t-i} \tau_{t-1} + \zeta_t $$
The first equation represents a set of measurement assumptions indicating that (1) over-time measures are assumed to be $\tau$-equivalent, except for true attitude change, and (2) that measurement error is random. It decomposes the variance in reports into two components, one due to the latent attitude ($tau_t$) and the other due to random measurement error ($\epsilon_t$). The second equation specifies a causal process involving attitude change over time. $\beta_{t,t-i}$ is the stability of the latent attitude during the period from $t-1$ to $t$. $\zeta_t$ represents sources of change over time in the latent attitude. The model assumes that the system of attitudes is in a dynamic equilibrium described by a lag-1 or Markovian process in which the distribution of a "true" attitude at time $t$ is dependent on the distribution at time $t-1$ and not on the distribution of the variable at previous times. 

As presented above, the model is unidentified. All strategies for estimating these quantities require the lag-1 assumption regarding the nature of "true" attitude change, as well as an assumption about measurement error. An approach proposed by Heise [@heise1969] assumes equal reliabilities over occasions of measurement. Another approach is to assume constant error variances rather than constant reliabilities [@wiley1970]. We follow the Heise approach and constrain reliabilities to be constant across waves, rather than constraining error variance to be the same. However, extensive work suggests that both models produce similar estimates of the standardized parameters [@alwin2007; @alwin1991]. 

We divide each sample into seven age categories: 18-25, 26-33, 34-41, 42-49, 50-57, 58-65, 66-83, assessed at the initial survey year. We analyze these estimates in two ways. First, we explore the stability of the latent attitudes, $\beta_21$ and $\beta_32$. These estimates are non-independent, so we examine them as multiple indicators of the stability of the attitude in that panel. We take these reliabilities as a measure of how much durable change in attitudes occurs in an issue during the panel, with higher values indicating less change. Second, we examine a single reliability estimate generated for each group for each attitude measure. We take this as a combined measure of actual measurement error and transitive, non-durable change that respondents make during the course of the panel. For each age group, we average across all questions in a given panel to generate an average estimate of reliability and an average estimate of stability for each age group in each panel. 

We compare these average estimates of reliability and stability for age groups across panels to evaluate our hypotheses.

## Question Fixed Effects

For questions that are asked in multiple panels, we also use estimates of stability and reliability as outcome variables in a regression on time with fixed effects for questions. We run these models separately for each age group. These models let us allow for an average trajectory of reliability and stability for age groups over time, controlling for questions, to evaluate whether respondents in the same age groups have become more or less stable reporters of the same opinions over time. We also control for attributes of panels that might affect reliability or stability estimates -- such as the shortened wave duration in the 1980 panel or the mode of administration -- by including panel fixed effects in the model as well. 

# Results

## Stability and Reliability

Before digging into the time trends, I first evaluate the average estimates for reliability and stability for each panel, and for each age group to establish a baseline of comparison. Table 1 presents the average reliability and stability for each panel. Across panels, the 1956 panel shows the lowest average reliability of all the panels.[^improvement] The 1980 panel, with the shortest time between waves, has notably higher reliability than other panels. This has been established in previous work [@krosnick1989]. Having less time between waves increases the reliability of responses, though the exact mechanism for this has not been explained. The remaining panels all have comparable reliabilities, with many within .02 of each other.

[^improvement]: This is potentially due to improvements in question-asking since the ANES first administered this survey. Many questions in this panel have been critiqued as difficult for average Americans to answer. 

Average stability estimates are generally comparable across panels, ranging withing a couple points of each other. Of note here is that differences between the GSS panels are quite large, with the 2008-10-12 panel showing the highest label of stability while the 2010-12-14 panel showing the lowest, even though these panels overlap considerably.

Table XXX presents the average reliability and stability for age groups. Here we see results broadly consistent with the "impressionable years" hypothesis. First, the 18-25 year old group has notably lower stability than other groups, suggesting higher rates of change in their "true" attitudes over time. Stability tends to increase up through middle age (42-29) before leveling off. Second, reliability is also substantially lower for the youngest age group and increases consistently as groups get larger. For both measures, the largest jump is between the youngest age group (18-25) and the one following it (26-33), supporting the impressionable years model over an increasing persistence model.

While these results suggest that life-course patterns that have been established in other work using earlier panels hold true in more recent panels, they do not say anything about whether changes in the life course have extended or intensified the "impressionable years" by decreasing stability and reliability in the youngest group (18-25) over time or extending the values seen in that group up the age ladder (to respondents in the 26-33 group). For that we must examine age groups separately by panel.

## Over-Time Trends

Table XXX summarizes the average reliability and stability estimated for each of the age groups for each of the panels analyzed. The "formative period" or "impressionable years" hypothesis and previous work [@alwin2007; @alwin1989] suggests that we should observe low reliabilities for the youngest cohorts and large and approximately equal in the older groups. It is important to note that some age-group/panel combinations have very small sample sizes, which can lead to large sampling errors and produce problematic estimates of reliability. Because of this, we remove some reliability and stability estimates that are outside the bounds of plausibility or were not able to be estimated. 

Because information in the table is difficult to process, Figure ... plots the average reliability estimates by year. The figure and table show the same overall age trend as the aggregate data. Young people are the least reliable respondents in most panels, suggesting high rates of non-persistnet change. Broadly, across panels, we see a general positive relationship between age and stability up through middle age, but a decrease in stability following that. This is consistent with some work suggesting that people "open up" for change later in life after a period of increased stability in middle age [@danigelis2007].

While respondents in other age groups have a generally positive trend in reliability, meaning they make less non-persistent change in more recent panels, the same is not true of the youngest age group. Members of this group have a flat age trend. At the same time, the same is not true of the second-youngest age group (26-33), which is where we might have expected to see the most significant shift over time. While this group tends to have the second-lowest average reliability over time, the trend for this age group is highly consistent with that of the rest of the population, displaying higher levels of reliability over time.

Turning to stability, we see a similar pattern. Figure XXX plots the average stability for each age group over time. Young people are consistently less stable opinion holders than the rest of the population. Stability generally increases with age, with a decline after middle age (sometimes getting as low as the 18-25 group. The gap between the 18-25 group and the 26-33 group is often the largest gap. However, we do not see a strong time effect among stability. Groups are all slightly more stable in more recent panels than in the early panels, but not enough to say there has been a significant shift in stability since the 1950s.

## Question Fixed Effects

The preceding analysis has assumed that panels are generally comparable, and that average estimates of reliability and stability are comparable across panels as measures of reliability and stability toward "salient" issues for that period. We now turn toward exploring the reliability and stability for questions that are asked in multiple panels. Table XXX presents regression coefficient estimates for model regressing stability estimates on time and fixed effects for question and panel, with an interaction between time and age group. The table shows that there is no discernible time trend for the stability estimates of 18-25 year olds, nor is their time trend statistically significantly different from the time trends for the other age groups. 

Table XXX presents similar coefficient estimates for the model regressing reliability on time and fixed effects for question, with an interaction between time and age group. The table also shows no meaningful time trend for respondents 18-25. The coefficient for the interaction between time and the 58-65 age group is statistically significant, suggesting people in this group became slightly more stable over time compared to 18-25 year olds, but it is difficult to make a clear judgment about the overall trend, and there are no other statistically significant interaction terms.

# Discussion

Theoretical models that explain the heightened malleability of attitudes during early adulthood by referencing the unique social conditions of that life phase would posit that significant changes in the timing of life course events should produce heightened rates of attitude change during early adulthood (18-25) or should extend rates of attitude updating later into life (ages 26-33). As Americans have pushed back marriage, childbirth, and entering the workforce, we should expect these to have some effect on the sources of attitude change, such as meeting new significant others, getting exposed to new kinds of information, or delaying social positions that expect stability. We tested that claim by looking at the stability and reliability of political attitude reports among different cohorts as they moved through the same age groups. 

The results from the preceding analyses suggest that the changing life course has had minimal impact on rates of attitude change in the population. Despite significant shifts in age of first marriage and age of first child birth, and a much higher proportion of the population attending higher education, attitude behavior as measured by reliability and attitude stability are remarkably similar over time. Across panels, we see consistent evidence that ages 18-25 have decreased attitude reliability and decreased attitude stability relative to the rest of the population, a pattern consistent with the "impressionable years" hypothesis that has broad support in the sociological literature. However, there is consistent change over time in either reliability or stability estimates for people in this age group. They are different from the rest of the population, but similarly different over time. It does not seem to be the case that the emergence of the "Age of Independence" since the middle of the 20th Century has increased attitude change among people in this group.

Similarly, as life course transitions have been pushed back since the middle of the 20th Century, we expected to see decreased reliability and stability extend into the next age group (ages 26-33). However we see no clear evidence of changes in either measure. These peoples' attitude behavior is consistently closer to the next oldest group (34-41) than the 18 to 25 age group. While social life for people in this group tends to resemble the younger group, their attitude behavior tends to resemble older groups. 

Controlling for changes in the kinds of questions asked using fixed effects models, we see no significant time trends for either stability or reliability. 

Overall, our findings suggest that the substantial shifts in the timing of life course transitions, increased rates of college-going, and other major social shifts that have occurred over the past 60 years has not affect attitudinal behavior in ways suggested by a "social" explanation for the "impressionable years" hypothesis would suggest. Instead, it seems that most of what makes the "impressionable" years impressionable has to do with age itself. This points toward biological or cognitive mechanisms about how people respond to new information over time as the key source of "impressionable years".

While we have focused on the time trend as the major question in our analysis, our results speak to a couple other domains of sociological inquiry. Our results reinforce findings that middle-aged respondents appear to have the most reliable and stable attitudes than members of other age groups. Respondents 50-65 consistently demonstrated the highest average reliability, with respondents over 65 displaying slightly lower levels of reliability. 

## Limitations

We face several limitations in trying to make broader claims. First, many of our age-group estimates of stability and reliability are based on relatively small samples and as a result are not highly reliabile. This is particularly true for the youngest and oldest age groups, which tend to be the smallest in each panel. We have not accounted for that imprecision in our analysis here. 

Second, while we look at more than 250 questions in panels spanning 60 years, we do not actually have a large number of distinct time points. In total, we only have eight estimates of "average stability" and "average reliability" for each age group. Four of our eight panels fall within the same decade (and three of these panels overlap). Again, given the large amount of unreliability in our estimates for groups, we cannot rule out the possibility that clearer trends would emerge with more data. It is not clear how to improve this limitation, as we can not go back in time and generate new panels.

Second, the high diversity of questions comes at the cost of not having many questions asked in multiple panels. Outside of the GSS panels (which span eight years total), most questions examined here are only asked in one panel. Of those that are asked in multiple panels, most are asked only twice, which gives us limited power for understanding change in reliability and stability net of change in question wording. It also forces us to assume that estimates of reliability and stability are comparable across panels as estimates of general reliability and stability of "political attitudes" at that time -- a claim that might not be valid.

# Conclusion

This paper set out to test whether the unique rates of attitude change found among young adults are due to the social features of this life stage or due to features of how human brains develop and process information over time. We leverage delays in the timing of life course transitions and the emergence of an "age of independence" over the past 70 years to explore whether attitude behavior shifted in response to these changes. We expected that we should see more durable attitude change in early adulthood and an extension of the "impressionable years" pattern up the age ladder.

We found no evidence of either process, broadly suggesting that changes in the timing of life course transitions, as well as broader social and cultural changes around early adulthood have not broadly affected attitude behavior among young adults. The pattern of results generally suggests that what makes early adulthood unique when it comes to attitude development is not its social conditions, but how humans process information as they age. These years are not formative because they are unfettered, they are formative because they are early.

# References


