---
title: Extended Early Adulthood and Attitude Change
author:
  - Kevin Kiley, North Carolina State University
  - Nicolas Restrepo, University of California, Davis
date: "7/06/2023"
output: 
  bookdown::word_document2: 
    fig_caption: yes
    reference_docx: word-styles-reference-02.docx
  bookdown::pdf_document2:
    keep_tex: true
    latex_engine: xelatex
    toc: false
    number_sections: true
bibliography: ["kileybib.bib"]
header-includes:
   - \usepackage{setspace}
   - \setlength{\parindent}{4em}
   - \setlength{\parskip}{0em}
   - \usepackage[markers,nolists]{endfloat}
   - \usepackage{graphicx}
mainfont: Minion Pro
fontsize: 12pt
abstract: Young adulthood is consistently identified as a “formative period” in the life course, when people have heightened probability of changing their personal culture. This probability has often been attributed to the social conditions of adolescence. Over the past 70 years, changes in the timing of major life course events such as marriage and childbirth have transformed and extended this life stage. We leverage these changes to explore whether life course changes, as well as broader social changes, have affected how likely people of different cohorts are to make durable changes of general political dispositions over a comparable time frame. We find strikingly little difference in the rates of any kind of stable opinions and opinion change among young people in different eras. People of all ages have similar attitude behaviors over time. The overall pattern suggests either that social conditions are not strongly related to attitude stability or that different social shifts have had counter-vailing effects that produce aggregate stability in rates. 
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Introduction

Adolescence and young adulthood are typically identified in social science literature as "impressionable years" -- a stage of the life course in which people are more susceptible to broad social currents, when their opinions are more malleable, and when peoples' core ideas and attitudes are formed [@krosnick1989; @alwin1991]. Research regularly finds that people are more likely to change their preferences, attitudes, and opinions in these life stages than other life stages, with opinions and dispositions becoming more stable once these life stages have passed [@sears2013; @kiley2020]. This pattern, in which young people are open to cultural change and become more resistant over time, underpins dynamics around cohortization that are frequently invoked in larger models of social change [@ryder1965; @mannheim1952].

However, why people in this life stage appear to show more frequent opinion change relative to older people is unclear. Explanations in the social sciences tend to highlight the unique social features of these life stages -- high rates of mobility between social contexts, participation in educational institutions, and cultural expectations about pursuing "new experiences" -- that shape how people are exposed to new sources of information or their ability to update opinions in the face of new information. Work in biology, psychology, and cultural evolution, in contrast, shows that peoples' cognition changes in ways that might make them more resistant to new information as they age [CITATION]. While both mechanisms likely play a role in facilitating opinion change in this life stage, the relative contributions of each are unclear.

Clarifying the relative importance of different mechanisms that drive the frequency of opinion change during this formative period is important for understanding the mutually reinforcing processes of social change and cultural evolution. If openness to cultural change in early adulthood is principally a function of the social structure of life during these ages, then delays in the timing and ubiquity of life course transitions like marriage and childbearing, and increases in college-going, could have significant effects on the broader process of macro-social change. Similarly, social changes such as the deinstitutionalization of marriage [@cherlin2004; @cherlin2021; @robbins2022] that decrease distinctions between life course stages might make older people more open to change in more recent eras than they were in earlier eras, diminishing the importance of "cohorts" for social change and increasing the importance of intrapersonal change over time. If the mechanisms are principally cognitive and biological, rather than social, then these changes are unlikely to affect rates of social change in the same way.

In this paper, we explore how changes in the broader social structure and changes in the timing of life course events since the 1950s have affected the stability and reliability of political attitudes over time, especially differences in rates of opinion change between young adults and the rest of the population. Over the course of the 20th century, the timing of life-course transitions such as completing schooling, entering the workforce, getting married, leaving one's parents' home, and having children have changed dramatically, with most of these event occurring later in the life course in more recent cohorts [@buchmann1989; @bruckner2005]. Similarly, the "early adulthood" stage of life has become more detached from family and other role obligations, giving people in this life stage more freedom to explore new ideas and lifestyle choices [@rosenfeld2009]. This suggests both a lengthening of and an intensification of this stage of the life course in ways that potentially affect the rates at which people undergo cultural change.

We take advantage of this change over time to explore whether young adults of different cohorts demonstrate more or less change in their political opinions over time relative to other members of the population. We decompose over-time responses into reliability (a lack of random, non-persisting fluctuations) and stability (true consistency in latent dispositions net of these random fluctuations) for a range of political attitudes in nine nationally representative panel data sets spanning from the 1950s through the 2010s. We separately estimate these parameters for a comparable set of age groups in each panel to evaluate whether response reliability or stability changed as new cohorts moved through the same age ranges under different social conditions.

Consistent with the "impressionable years" hypothesis, we find that the youngest respondents in each panel (ages 18-25) are consistently the least stable opinion reporters, suggesting they are more likely than other respondents to make durable changes in their views. They are also among the least reliable reporters, suggesting considerable short-term but non-persisting change in their views. But we find no consistent trajectory in either measure over time, among members of this age group or other members of the population. Notably, respondents aged 26 to 33 continue to look more like older age groups than the youngest age group in their rates of opinion stability and reliability, providing little evidence of "lengthening" of this formative window.

We believe these findings have important implications for our understanding of why early adulthood is a significant formative period. While these findings do not provide conclusive evidence of one mechanism over the other, they confine the range of potential theories about the relationship between life course stages and attitude change. They suggest that there is something relatively timeless -- potentially biological and cognitive factors -- that accounts for increased opinion variance in young people, and that, barring significant evidence of counter-currents that stabilize people, changes in the social conditions of early adulthood have not increased the degree to which young people make meaningful changes of opinion.

# Impressionable Years

The idea that the early stages of the life course are especially influential in the process of attitude formation is dominant across contemporary accounts of socialization [@dinas2014; @guhin2021]. The principal argument across a range of perspectives is that the circumstances in which people are brought up leave an enduring and traceable mark on their personal culture -- worldviews, attitudes, dispositions, behaviors, and preferences [@gerber1998]. In the study of political socialization, this perspective enjoys a longstanding history. "Generational effects" are used to explain the development of political preferences, longitudinal shifts in attitudes, and differences across age-groups [@mannheim1952; @bartels2014]. However, the notion of "impressionable years" is more general than just political preferences. The concept of cohort effects -- widespread in sociology -- rests on the assumption that peoples' early years play key role in shaping not just political opinions, but peoples' cognition on many dimensions, shaping their choices and life outcomes well beyond the time when this period has passed [@elder2016]. Similarly, practice theories associated with Bourdieu suggest that the "past conditions of production" durably shape peoples' cognition, reactions, and behavior well into adulthood [@bourdieu1990]. Thus, the notion of a formative period at the early stages of the life-course underpins diverse and longstanding theories of behavior.

These models of social imprinting have implications for the kinds of patterns we should observe in a population's attitudes over time and suggest specific forms that within-person opinion change should take over time. The "impressionable years" hypothesis -- that people demonstrate more opinion change early in life followed by a period of relative stability, especially in middle age -- has often been tested against other theories of opinion change over the life course. The most common alternatives are an "aging stability" or "increasing persistence" hypothesis that argues that openness to change gradually declines over time and a "life stages" hypothesis, in which people are open to attitude change both early in life and later in life, with stability principally happening in middle ages [@visser2004a]. While different attitudes occasionally follow different patterns, the impressionable years hypothesis has generally been shown to be true for broad political ideology, partisan identification, and specific policy preferences [@krosnick1989; @alwin1991; @sears1999]; social attitudes [@danigelis2007]; and interest in politics [@prior2010]; as well as things like personality traits [@wagner2019]. More generally, recent research has found that, with a few notable exceptions of high-salience events such as national shifts around gay rights, durable change of social opinion is quite rare among U.S. adults [@kiley2020], and Vaisey and Lizardo [-@vaisey2016] find that cohort -- the year of a person's birth - explains much more variance than period -- the year of observation -- for most items in the General Social Survey, suggesting a strong impressionable years pattern.

In recent years, researchers have attempted to use new approaches to quantify "openness" to social influence across the life course, especially around politics [@bartels2014; @ghitza2022]. This work has produced remarkably similar patterns with openness peaking from a person's mid-teens through age 25 and declining quickly after that, lending more credence to the "impressionable years" hypothesis [a pattern that seems to hold for music tastes as well @way2019]. However, this work tends to assume a constant age-based rate of openness across cohorts -- that 20-year-olds in 1950 are open to influence at the same rate as 20-year-olds in 2010 -- which has not been tested.

# Theoretical Models

Why is it research consistently finds the period of time between 14 and 25 to be distinctly "impressionable years?" At the outset, it is important to note that changing cultural dispositions like attitudes involves at least two distinct processes that can be difficult to disentangle: exposure to new information and openness to change conditional on exposure to new information. For example, it could be the case that people of all ages are exposed to new ideas at similar rates, with acceptance of a new idea being a function of age, which would account for age-based patterns in opinion change. Conversely, it could be the case that rates of exposure to new ideas changes over the life course, while openness to changing one's mind as a function of exposure does not, producing the same pattern. It could also be the case that both change as a function of age. Because these mechanisms have not been disentangled, in this section we outline theoretical processes that have been suggested to contribute to one or both of these processes.

## Biological Mechanisms

The first potential mechanism for changes in attitude stability over time is rooted in the biology of the human brain and science of how people process information. This approach tends to suggest that human cognition works similar to Bayesian updating, in which humans weight all information they are exposed to equally, whether they encounter it during adolescence or middle age, and are exposed to information at a (more or less) constant rate [@bartels2014; @gopnik2020; @sherratt2018]. However, because people have already encountered a lot of information by the time they reach adulthood, each new piece of information encountered later has less of an impact on their overall dispositions [@bartels2014]. From this perspective, the distinctive thing about our early years is simply that they happen early, and they prove so influential because the incremental effect of new information diminishes as we age.

It is also possible that there is something unique about human cognition during these periods making people ascribe more weight to the information acquired within them than to information acquired at other points. Maturational arguments about the increased plasticity of human brains during our early years are consistent with this position, as our brains appear to exhibit more malleability during childhood and adolescence than later in life [@mata2015]. Supporting this model is evidence that early formative periods have been observed not just in people, but across species. In a study of social learning among birds, for instance, Aplin and colleagues [-@aplin2017] show that younger birds -- unlike their older counterparts -- were consistently able to retool their habits in light of new information.

In light of empirical evidence about these sensitive windows across species, there has been modeling work about why periods of heightened sensitivity would emerge and what contexts would facilitate their emergence (Fawcett and Frankenhuis 2015). The central argument from this work is that that the emergence and timing of these sensitive windows depends on the interaction between the access to information, the reliability of information, and the stability of the environment, and that early formative periods are likely to evolve when environments are unstable and information is plentiful yet unreliable (Frankenhuis and Walasek 2020). In these circumstances, it makes sense for agents to explore early on, to find something that works, and then to stick to strategies that have worked well in the past. Access to different types of information might vary across time and this might explain the emergence of sensitive periods at later stages of the life-course (Walasek, Frankenhuis, and Panchanathan 2021). For example, the importance of musical tastes and fashion choices becomes important around adolescence, and, at this stage, we are awash with at best contradictory information about what one should or should not like, or should or should not wear. Sensitive periods around the development of these tastes might peak around this period, when there are more signals and when the payoffs are more salient.

The thrust of the biological arguments is that, irrespective of the social conditions they inhabit, millennia of evolution have led to the development of a cognitive architecture that makes humans relatively open changing dispositions at younger ages and relatively resistant at older ages. However, while biological mechanisms can shape how individuals respond to new information when they encounter it, these processes cannot dictate the rate at which individuals are exposed to new information, which might also matter for rates of opinion change. For that, we must turn attention to the structuring of the social world.

## Life Course and Social Roles

Humans' early years might be distinct in terms of cognitive plasticity, but they are also socially distinct, characterized by sustained social learning and constant changes of social contexts. Here we briefly consider some of the ways that the "impressionable years" differ in ways that might expose people to new information at higher rates and also affect their willingness to update beliefs, beyond what cognition might allow.

First, people in this age group tend to move across social contexts at a much higher rates than people in other age groups. In the 11-year window from ages 14 to 25, in which people tend to show the highest rates of opinion updating, young people move from middle school to high school to either higher education or the workforce or both, with each year potentially exposing people to new classmates, teachers and other role models, and sources of information. People in this age window also show the highest rates of residential mobility, moving for educational and occupational reasons. Assuming that new social contexts shape exposure to new information, this heightened contextual mobility during this stage might explain part of the difference between age groups.

Second, people in the "impressionable years" window spend their time in different social contexts than people in middle age. Data from the American Time Use Study shows that people under age 25 spend a larger portion of the day on leisure time and educational activities and a smaller part of the day doing work and work-related activities than people between the ages of 25 and 55. These contexts, especially education, are designed to expose people to new information in ways that can lead to new opinions. For example, there is some evidence that college attendance leads to changes in opinions about civil liberties, political views, gender egalitarianism, and racial inequality [@campbell2016; @wodtke2018; @edelmann2023]. Social networks also differ in this time period. Young peoples' networks tend to be larger and include more friends than kin, for example [@marsden1987]. It could be the case that these larger "weak tie" networks expose younger people to more new information that drives opinion change [@granovetter1973; @burt2005].

Third, these are periods are also culturally distinct, with exploration and self-discovery expected and encouraged. People in this "early adulthood" phase are not expected to be stable adults, something should not be taken for granted given social variation in norms around when maturity is reached [@cunningham2007; @elder1994].

## Updating Conditional on Exposure

While the distinct social and cultural conditions of adolescence and early adulthood might expose young people to new information at higher rates than older people, the impact of this information on peoples' attitudes is contingent on their ability to incorporate it into their cultural repertoire. The social conditions of different life stages might make it easier or more difficult for people to act on these new sources of information in ways that facilitate opinion change.

Social networks not only shape peoples' exposure to new information, but they also affect the degree to which people adopt new beliefs and attitudes. People are much less likely to defect from their traditional beliefs and adopt new beliefs if they are embedded in dense networks [@stark1980]. Consistent with this, mid-life is associated with denser, more homogenous networks [@marsden1987; @diprete2011], which experimental research suggests reduces the propensity to adopt new beliefs [@visser2004]. If young people exist in less dense, more heterogeneous social networks, it might be easier for them to update their networks to reflect new beliefs rather than constrain their beliefs to their social networks. Similarly, if information flows less freely through weak-tie networks, these structures might allow respondents to limit their exposure to or close off parts of their lives to people who might not be supportive of new attitudes.

Previous work on opinion stability over the life course suggests that people tend to value stability in figures holding social power. As people move into roles with more social power in mid-life, both in family and occupational contexts, they potentially feel this expectation from others and act accordingly, closing themselves off to updating beliefs even as they are exposed to new information [@eaton2009]. This potentially explains another phenomenon: that people appear to open up to changing their minds again as they enter later life and retirement, when these expectations presumably diminish [@danigelis2007].

# Changing Life Course

Given the distinct social conditions of the early-adult phase of life, there are significant reasons to believe that the "impressionable years" are principally an effect of how societies choose to structure the life course or the interaction between these life course stages and biological mechanisms. Because of this, contemporary historical trends offer a window to disentangle the role of socio-cultural and biological or cognitive factors in explaining why we observe "impressionable years."

In the United States, the last seven decades have seen considerable social and cultural changes around adolescence and young adulthood [@buchmann1989; @rosenfeld2007; @rosenfeld2005]. The expansion of higher education and increased possibilities for mobility are among the many social processes that have led to changing expectations for the trajectories that young adults should follow [@rosenfeld2007]. These changes have made life course trajectories less predictable, and the "script" of young adulthood has become less rigid: it might involve prolonged higher education, moving to a different city, or dating without a stable romantic partner [@buchmann1989]. For the purposes of this paper, there are two related trends that are particularly important: the elongation of young adulthood and the intensification of this life stage.

## Timing

First, the period between adolescence and "settling down" has been getting longer over time, and this might affect the patterns of attitudinal updating we expect to see for the same age groups in different cohorts. Buchmann [-@buchmann1989] finds that the diversification of life-trajectories has been accompanied by the postponement of the rituals associated with adulthood. In the United States, both the median age at first marriage and median age of first child birth has consistently risen since the mid-20th Century [@rosenfeld2009]. We also see higher rates of non-marital childbearing across all demographic groups [@cherlin2021]. Thus, the markers of the transition into adulthood seem to be occurring at later ages and potentially in different orders for more recent cohorts.

If the distinctive nature of "impressionable years" is principally driven by their unique social circumstances, then these shifts have the potential to extend these social circumstances into later ages. This, in turn, could have an effect on how long exploration, and therefore openness to durable change, lasts throughout the life-course. If this is the case, we should expect to see lower levels of attitude stability (and therefore more change) among age groups that, for earlier cohorts, displayed mainly stability. In other words, people who were born in the mid-20th century would have displayed mainly attitudinal stability by the time they reached their mid-twenties while more contemporary counterparts might still show cultural change when they reach that age. Specifically, we expect the attitude behavior of people aged 25-33 to more closely resemble middle-aged respondents in earlier cohorts [@krosnic1991; @alwin1991] but younger respondents in more recent cohorts. This produces our first hypothesis:

**Hypothesis 1: Rates of attitude stability will be lower among respondents aged 25-33 in recent surveys than in earlier surveys.**

## Intensifying Impressionable Years

A second trend in early adulthood relates to just how much exploration young adults can engage in during these "impressionable years." In his work, Rosenfeld [-@rosenfeld2007] argues that one of the processes underlying the rapid rise in same-sex and interracial marriages in the United States is that young adults are increasingly escaping the controlling gaze of their parents. When a young person lives with, or is financially dependent on, his or her parents, the latter have more say about their child's choice of partner. Social and cultural changes that have increased geographic mobility and independence from parental authority mean people in this life stage have been able to engage in courtship outside the gaze of their parents, making choices that would not have been sanctioned by them.

Rosenfeld's work suggests that the social conditions that shape where we spend our impressionable years might also shape how much exploration we can engage in. An increase in independence might entail more exploration, and greater ability to update attitudes as a result of this exploration. This assertion in turn engenders a prediction: we should see more attitudinal updating among young adults in recent years than among young adults in earlier eras, even if they have met similar life-course milestones.

This approach suggests that it is not the timing of life events that is important for rates of change, but the broader social conditions of early adulthood that might make people more malleable in recent cohorts. In other words, unmarried, childless 25-year-old men and women in 1956 might have experienced a set of social constraints that unmarried, childless 25-year-old men and women in 2008 do not experience, leaving the latter much more open to developing new opinions than their predecessors. The "intensification" of impressionable years suggests two hypotheses.

*Hypothesis 2: People ages 18 to 25 will demonstrate lower levels of reliability in more recent years than in earlier years.*

Reliability reflects not just the degree to which people make errors in their reporting of attitudes over time, but the baseline level of variance around a fixed attitude position that people express. In other words, we might ... if younger people bounce around 

*Hypothesis 3: People aged 18 to 25 will demonstrate lower levels of stability in recent years than they did in earlier years.*

## Biological and Cognitive Factors

We have framed our hypotheses as expectations derived from the framework suggesting that social conditions play a large role in explaining the uniquely high rates of attitude change among early adults and adolescents. However, to the extent that we do not see evidence that these social changes have not contributed, but that young adults maintain a similar pattern of lower rates of attitude stability that older adults over time, we take this as evidence that social circumstances play a relatively small role in explaining change in favor of biological and cognitive factors.

# Analytical Strategy

## Data and Methods

Analyzing these questions requires data on attitude reports over time for members of different cohorts at different time points, presumably coming from the same population. While ideally we would be able to observe different cohorts responding to the same broad range of questions as they pass through the same age periods, we do not know of such a data source.

Instead, we focus on a range of questions tapping a similar domain -- national politics in the United States. We draw on data from seven different panels administered since the 1950s. These include four major panels administered by the American National Election Study in 1956-58-60, 1972-74-76, 1992-94-96, and 2000-02-04. These were all administered over a four-year period, with waves two years apart and contain a diverse array of attitudinal questions. We also use the General Social Survey's rotating panels from 2006-08-10, 2008-10-12, 2010-12-14. We also include the 1980 Major Panel study from the American National Election Study, a four-wave panel spanning about eight months. Finally, we incldue the the 1990-91-92 Merged File, a three-wave panel spanning two years. All seven surveys reflect nationally representative samples of U.S. households.

In all panels, we identified questions that tap several categories of political attitudes: (1) political efficacy and alienation; (2) attitudes toward social groups (such as labor unions, blacks, whites, the police, Democrats, liberals, etc.); (3) attitudes toward both domestic and policy issues; (4) ideological identification on a liberal-conservative scale; and (5) partisan identification. For the 1956-60, 1972-76, and 1980 panels, we broadly follow Krosnick and Alwin's selection of variables [-@krosnick1989]. In the 1992-96 panel, we follow Alwin's identification of questions [-@alwin2007]. For the 1990-92 panel, the 2000-04 panel, and the three GSS panels, we identify questions similar to those identified in the earlier panels.

This produces a set of 265 panel-attitude measures asked on a variety of scales tapping a diverse array of topics related to national government and politics in the United States. They include four- and five-point Likert scales, binary agree/disagree response scales, 100-point "feeling thermometers", and a range of other structures.

Most questions are asked in only one panel, but a small number of questions are replicated exactly across at least two panels (excluding questions duplicated across the GSS panels, where all questions are duplicated). There are theoretically relevant trade-offs from focusing only on the same questions over time. By focusing on the same questions over time, we control for question content and structure. If attributes of questions changes over time, that might affect the estimates of stability or reliability. However, the questions asked in major surveys change over time as the dominant issues change. By focusing only on questions that are repeated across eras, we limit our attention only to issues that have been salient for an extended period of time. These might behave different than the "issues of the day" -- they might get settled earlier in life, be more resistant to change, or be reported more reliably than other kinds of questions.

By focusing on all questions tapping the domains outlined above, the average level of stability and reliability reflect change in "important" issues -- including issues that remain important for a long time and issues that only maintain salience for a few years.

To ensure that our findings are robust to both sets of issues, we conduct a separate analysis of questions that are repeated across multiple panels (excluding questions replicated just across the GSS). These include partisan identification (asked in all panels), political ideology on a seven-point liberal-conservative scale (asked in \## panels), questions about federal spending on different priorities (asked in the 1990 and 2000 ANES panels and the GSS panels), and questions about government efficacy and alienation from the political process (asked in the 1970s, 1990s, and 2000 ANES panels), as well as others.

Weighting schemes are different across panels. When available, I use weights that account for differential selection. The 1972-76, 1980, and 

## Methods of Analysis

There are a number of potential ways to measure change, including linear trajectory models, latent growth curve models, and sequence analysis. We follow previous work that seeks to separate true change in attitude response from measurement error in the study of attitude change and stability over the life cycle. To do this, we follow Alwin and Krosnick's approach of using just-identified simplex models that specify two structural equations for a set of three over-time measures of a given variable, $y_i$:

$$ y_{t} = \tau_t + \epsilon_t$$

$$ \tau_t = \beta_{t,t-i} \tau_{t-1} + \zeta_t $$ The first equation represents a set of measurement assumptions indicating that (1) over-time measures are assumed to be $\tau$-equivalent, except for true attitude change, and (2) that measurement error is random. It decomposes the variance in reports into two components, one due to the latent attitude ($tau_t$) and the other due to random measurement error ($\epsilon_t$). The second equation specifies a causal process involving attitude change over time. $\beta_{t,t-i}$ is the stability of the latent attitude during the period from $t-1$ to $t$. $\zeta_t$ represents sources of change over time in the latent attitude. The model assumes that the system of attitudes is in a dynamic equilibrium described by a lag-1 or Markovian process in which the distribution of a "true" attitude at time $t$ is dependent on the distribution at time $t-1$ and not on the distribution of the variable at previous times.

As presented above, the model is unidentified. All strategies for estimating these quantities require the lag-1 assumption regarding the nature of "true" attitude change, as well as an assumption about measurement error. An approach proposed by Heise [@heise1969] assumes equal reliabilities over occasions of measurement. Another approach is to assume constant error variances rather than constant reliabilities [@wiley1970]. We follow the Heise approach and constrain reliabilities to be constant across waves, rather than constraining error variance to be the same. However, extensive work suggests that both models produce similar estimates of the standardized parameters [@alwin2007; @alwin1991].

We divide each sample into seven age categories: 18-25, 26-33, 34-41, 42-49, 50-57, 58-65, 66-83, assessed at the initial survey year. We analyze these estimates in two ways. First, we explore the stability of the latent attitudes, $\beta_21$ and $\beta_32$. These estimates are non-independent, so we examine them as multiple indicators of the stability of the attitude in that panel. We take these measures of stability as a measure of how much durable change in attitudes occurs in an issue during the panel, with higher values indicating less change. Second, we examine a single reliability estimate generated for each group for each attitude measure. We take this as a combined measure of actual measurement error and transitive, non-durable change that respondents make during the course of the panel. For each age group, we average across all questions in a given panel to generate an average estimate of reliability and an average estimate of stability for each age group in each panel.

We compare these average estimates of reliability and stability for age groups across panels to evaluate our hypotheses.

## Question Fixed Effects

For questions that are asked in multiple panels, we also use estimates of stability and reliability as outcome variables in a regression on time with fixed effects for questions. We run these models separately for each age group. These models let us allow for an average trajectory of reliability and stability for age groups over time, controlling for questions, to evaluate whether respondents in the same age groups have become more or less stable reporters of the same opinions over time. We also control for attributes of panels that might affect reliability or stability estimates -- such as the shortened wave duration in the 1980 panel or the mode of administration -- by including panel fixed effects in the model as well.

# Results

## Life Course Changes

While not the central question of our analysis, we first highlight changes in three life-course measures -- proportion of respondents who are married, proportion of respondents who have at least one child, and proportion of respondents who have a college degree -- across the panels we include in our analysis to illustrate the substantial shifts social conditions of early adulthood. The measurement of children varies between panel, sometimes asking respondents how many children they have ever had and sometimes asking respondents how many children currently live in their home. These responses are often similar for people in younger age groups, but produces very different responses in respondents in older age groups who have children that no longer live with them. For that reason, we hold respondents 50 and older off of the figure.

In the early panel (1956-60), respondents in the lowest age group look very similar to respondent in the older groups on all major measures. However, they quickly diverge by the 1970s, displaying the lowest probability of being married and the lowest probability of having children by quite a larger margin. Over time, the next youngest agr group (26-33) starts to diverge toward the youngest age group, especially in terms of marriage.

These trends set the stage for what to expect in terms of reliability and stability. To the extent that these measures as proxies for life stages that influence attitude stability and reliability, then we should see the youngest age group look similar to the older age groups in the 1950s, and diverge by the 1970s, continuing to diverge over time. Respondents in the 26-33 age group should remain similar to older respondents for most panels, but begin to diverge by the 1990s and especially by the 2000s.

## Stability and Reliability

We first evaluate the average estimates for reliability and stability for each panel and for each age group to establish a baseline of comparison. Table 1 presents the average reliability and stability for each panel. Across panels, the 1956-58-60 panel shows the lowest average reliability of all the panels.[^badq] The 1980 panel, with the shortest time between waves (about 3 months between each wave), has notably higher reliability than other panels, a fact established in previous work [@krosnick1989]. Having less time between waves increases the reliability of responses. The remaining panels all have comparable average reliabilities, with many within .02 of each other.

[^badq]: This is potentially due to improvements in question-asking since the ANES first administered this survey. Many questions in this panel have been critiqued as difficult for average Americans to answer.

Average stability estimates are also generally comparable across panels, ranging withing a couple points of each other. Of note here is that differences between the GSS panels are quite large, with the 2008-10-12 panel showing the highest label of stability while the 2010-12-14 panel showing the lowest, even though these panels contain the exact same questions and overlap considerably in terms of time.

Table XXX presents the average reliability and stability for age groups. Here we see results broadly consistent with the "impressionable years" hypothesis. First, the 18-25 year old group has notably lower stability than other groups, suggesting higher rates of change in their "true" attitudes over time. Stability tends to increase up through middle age (42-29) before leveling off. Second, reliability is also substantially lower for the youngest age group and increases consistently as groups get larger. For both measures, the largest jump is between the youngest age group (18-25) and the one following it (26-33), supporting the impressionable years model over an increasing persistence model.

These results reinforce life-course patterns established in other work and extend it to more recent panels, but they do not say anything about whether changes in the life course have extended or intensified the "impressionable years" by decreasing stability and reliability in the youngest group (18-25) over time or extending the values seen in that group up the age ladder (to respondents in the 26-33 group). For that we must examine age groups separately by panel.

## Over-Time Trends

Table XXX summarizes the average reliability and stability estimated for each of the age groups for each of the panels analyzed. The "formative period" or "impressionable years" hypothesis and previous work [@alwin2007; @alwin1989] suggests that we should observe low stability for the youngest cohorts and large and approximately equal stability in the older groups. The "extended early adulthood" hypotheses suggests that, over time, people in the 26-33 age group should come to more closely resemble people in the 18-25 age group, meaning their average stability will decrease over time as people in this age group continue to make durable changes of culture. The "intensification" of early adulthood hypothesis suggests that 18-25 year olds (and possible 26-33 year olds) will move farther apart from the rest of the population, both in terms of stability and reliability, as they make more temporary changes (lower reliability) and durable changes (lower stability) over time.

It is important to note that some age-group/panel combinations have very small sample sizes, which can lead to large sampling errors and produce problematic estimates of reliability. Because of this, we remove some reliability and stability estimates that are outside the bounds of plausibility or were not able to be estimated. If a question produced an impalusible value for one of the age groups, we remove it for all age groups.

Because information in the table is difficult to process, and because some of the panels have much higher average levels of stability and reliability because of shorter duration, Figure ... plots the average reliability estimates by panel, with each panel pegged to year it begain (e.g., the 1972-74-76 panel is plotted at 1972). The figure and table show the same overall age trends as the aggregate data. Across panels, the youngest respondents (ages 18-25) are the least stable respondents. In eight of the nine panels, they have the lowest average stability, and in the remaining panel, they have the second-lowest. However, there is no clear age pattern beyond that. Respondents in the second-youngest age group (26-33) have the second-lowest stability in only two of the panels (1990 and 2008), but this does not seem to indicate a pattern. In other panels, both early and late, these respondents seem indistinguishable from other respondents, especially in the 2006-10 and 2010-14 GSS panels (the most recent).

There is no clear time trajectory for any age group when it comes to stability, even accounting for different average duration across panels. Groups do not, on average, appear to be getting more or less stable over time, with responses from the most recent GSS panels looking quite similar to responses from the 1972-76 ANES panel. 

Turning next to the question of reliability, the youngest aged group (18-25) are typically among the least reliable respondents in each panel, suggesting they are making higher rates of non-durable change in their attitudes than other member of the population. However, the pattern is not as consistent as with stability, and there is not always a clear gap between the youngest and the rest of the population. Other groups -- especially the oldest (66-83) -- frequently show less reliability in each panel. In terms of reliability, the second-youngest group (26-33) are functionally indistinguishable from middle-aged respondents in each panel, and much closer to those respondents than the youngest, providing no evidence for the "extended formative period" hypothesis. Again, as with stability, these findings reflect previous work on reliability and show that patterns continue in more recent panels.

In terms of change over time, there appears to be a slight upward trend in reliability across the panels, even accounting for the two panels with different duration -- the 1980 and the 1990-91-92 ANES panels. However, aside from the general upward trend, there do not appear to be distinct time trends for any of the age groups.

## Question Fixed Effects

The preceding analysis has assumed that panels are generally comparable, and that average estimates of reliability and stability are comparable across panels as measures of reliability and stability toward "salient" issues for that period. We now turn toward exploring the reliability and stability for questions that are asked only in multiple panels. Table XXX presents regression coefficient estimates for model regressing stability estimates on time and fixed effects for question and panel, with an interaction between time and age group. The table shows that there is no discernible time trend for the stability estimates of 18-25 year olds, nor is their time trend statistically significantly different from the time trends for the other age groups.

Table XXX presents similar coefficient estimates for the model regressing reliability on time and fixed effects for question, with an interaction between time and age group. The table also shows no meaningful time trend for respondents 18-25. The coefficient for the interaction between time and the 58-65 age group is statistically significant, suggesting people in this group became slightly more stable over time compared to 18-25 year olds, but it is difficult to make a clear judgment about the overall trend, and there are no other statistically significant interaction terms.

# Discussion

Theoretical models that explain the heightened malleability of attitudes during early adulthood by referencing the unique social conditions of that life phase suggest that significant changes in the timing of life course events should produce heightened rates of attitude change during early adulthood (18-25) or should extend rates of attitude updating later into life (ages 26-33). As Americans have pushed back marriage, childbirth, and entering the workforce, we should expect these transitions to have some effect on the sources of attitude change, such as meeting new significant others, getting exposed to new kinds of information, or delaying social positions that expect stability. We tested that claim by looking at the stability and reliability of political attitude reports among different cohorts as they moved through the same age groups.

The results from the preceding analyses suggest that the changing life course has had minimal impact on rates of attitude change in the population. Despite significant shifts in age of first marriage and age of first child birth, and a much higher proportion of the population attending higher education, attitude behavior as measured by reliability and attitude stability are remarkably similar over time. Across panels, we see consistent evidence that ages 18 to 25 have lower attitude stability and potentially lower attitude reliability relative to the rest of the population, a pattern consistent with the "impressionable years" hypothesis that has broad support in the sociological literature. However, there is no consistent change over time in either reliability or stability estimates for people in this age group. They are different from the rest of the population, but similarly different over time. It does not seem to be the case that the emergence of the "Age of Independence" since the middle of the 20th Century has increased rates of attitude change among people in this group.

Similarly, as life course transitions have been pushed back since the middle of the 20th Century, we expected to see decreased reliability and stability extend into the next age group (ages 26-33). However we see no clear evidence of changes in either stability or reliability. Attitude behavior of people in this group is consistently closer to that of people in the next oldest group (34 to 41) than to people the 18 to 25 age group. While social life for people in this group increasingly resembles the younger group, their attitude behavior tends to resemble older groups.

It does not appear that the lack of change is attributable to changes in questions over time. We observe the same patterns in stability and reliability of attitudes whether we focus only on questions that are replicated across panels .

## Limitations

We face several limitations in trying to make broader claims. First, many of our age-group estimates of stability and reliability are based on relatively small samples and as a result are not highly reliabile. This is particularly true for the youngest and oldest age groups, which tend to be the smallest in each panel, meaning we have the least confidence in each individual group-question estimate for these groups. We have attempted to limit this problem by averaging as many items as possible for each panel, but the number of questions in each panel is highly variable. 

Second, while we look at more than 250 questions in panels spanning 60 years, we do not actually have a large number of distinct time points. In total, we only have nine estimates of "average stability" and "average reliability" for each age group. Four of our nine panels fall within the same decade, and three of these panels overlap. Again, given the large amount of unreliability in our estimates for groups, we cannot rule out the possibility that clearer trends would emerge with more data. It is not clear how to improve this limitation, as we can not go back in time and generate new panels.

Relatedly, most the panels span two presidential election years, in which respondents might be exposed to more information about national politics than usual that might produce heightened attitude change. Because of that, our results might not speak to other kinds of questions related to religion, and the patterns we observe might not be applicable to all times. 

Second, the high diversity of questions comes at the cost of not having many questions asked in multiple panels. Outside of the GSS panels (which span eight years total), most questions examined here are only asked in one panel. Of those that are asked in multiple panels, most are asked only twice, which gives us limited power for understanding change in reliability and stability net of change in question wording. It also forces us to assume that estimates of reliability and stability are comparable across panels as estimates of general reliability and stability of "political attitudes" at that time -- a claim that might not be valid.

# Conclusion

This paper set out to test whether the unique rates of attitude change found among young adults are due to the social features of this life stage or due to features of how human brains develop and process information over time. We leverage delays in the timing of life course transitions and the emergence of an "age of independence" over the past 70 years to explore whether attitude behavior shifted in response to these changes. We expected that we should see more durable attitude change in early adulthood and an extension of the "impressionable years" pattern up the age ladder.

We found no evidence of either process, broadly suggesting that changes in the timing of life course transitions, as well as broader social and cultural changes around early adulthood have not broadly affected attitude behavior among young adults. The pattern of results generally suggests that what makes early adulthood unique when it comes to attitude development is not its social conditions, but how humans process information as they age. These years are not formative because they are unfettered, they are formative because they are early.

# References
