---
title: "Modeling Change"
author: "Kevin Kiley"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Model

Panels differ in both the number of times respondets are asked a particular question as well as the duration between observations.

In the one-item, one-panel case (partisan identification in the 1972-76 panel, for example), we could model the absolute change from wave-to-wave as a function of the duration between observations (more time between waves should lead to more change). 

$$ y_{i} = \beta_0 + \beta_1*d_i + \epsilon_i $$

In this formulation, $\beta_0$ captures the expected absolute change in responses over time when the duration between waves is 0, or, more intuitively, the random deviation between waves that is unrelated to durable change (random noise). Conversely, $\beta_1$ captures the expected expected change one a one-unit (year) change in duration of observation, or the amount of absolute change we would expect over-and-above the change driven by random noise ($\beta_1$). 

Our theoretical question deals primarily with whether these coefficients change over time. In particular, we want to know whether people demonstrate more or less real change over time. To explore that, we can interact these measures with time. 

$$ y_{i} = \beta_0 + \beta_1d + \beta_2t + \beta_3(d*t) + \epsilon_i $$

In this formulation, $\beta_2$ captures the change in the baseline level of random change over time. A negative value of $\beta_2$ would suggest that people are becoming more consistent reporters of their true underlying opinion over time. $\beta_3$ captures the expected change in absolute change over time for a one-year change in duration. A positive $\beta_3$ value would suggest that people are more likely to undergo a "real" change in their opinion over time in later panels than earlier panels. 


Now how do we model this with multiple questions?

$$ y_{ij} = \beta_{0j} + \beta_{1j}d + \beta_{2j}t + \beta_{3j}(d*t) + \epsilon_i $$

Where:

$$ \beta_{0j} = \gamma_0 + \upsilon_{0j} $$
$$ \beta_{1j} = \gamma_1 + \upsilon_{1j} $$
$$ \beta_{2j} = \gamma_2 + \upsilon_{2j} $$
$$ \beta_{3j} = \gamma_3 + \upsilon_{3j} $$

In this framework, each item is assumed to have its own intercept and and effects for time, duration, and their interaction, but these... 

